[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://zeotask.netlify.app/*"
  to = "https://task.zeospec.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "unsafe-none"
